name: ci
run-name: "build & test"

on: [push]

jobs:
  build-n-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt install -y build-essential cmake

      - name: Build & Test
        run: |
          mkdir -p build
          cd build
          cmake .. && cmake --build .
          ctest
